# Generated by Django 4.0.5 on 2022-06-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=2)),
                ('date_of_birth', models.DateField()),
                ('industry', models.CharField(max_length=254)),
                ('salary', models.FloatField()),
                ('years_of_experience', models.IntegerField()),
            ],
        ),
    ]
