# Generated by Django 4.0.5 on 2022-06-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='years_of_experience',
            field=models.IntegerField(null=True),
        ),
    ]
