# Generated by Django 4.0.5 on 2022-06-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_employee_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='industry',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
