# Generated by Django 4.0.5 on 2022-06-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_employee_gender_alter_employee_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
